### ISSUE TITLE
update media elements js

### ISSUE THREAD

**Issue by WindowsRefundDay** [snarly/yt6#2]
the media elements player is really outdated. it would be nice if you updated it

**Comment by snarly** [comment]
Of course it is. The whole point of this project was to keep as many browsers and devices, both old and new, compatible with YouTube as possible. That goal required outdated stuff to be present in the code over the past 8 years.

But alas, YouTube did its best to make it impossible to reinvigorate stuff beyond a certain age.

**Comment by WindowsRefundDay** [comment]
> Of course it is. The whole point of this project was to keep as many browsers and devices, both old and new, compatible with YouTube as possible. That goal required outdated stuff to be present in the code over the past 8 years.
> 
> But alas, YouTube did its best to make it impossible to reinvigorate stuff beyond a certain age.

that is serious dedication man, respect 🙏
